/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'skobr' at '10/29/17 7:49 PM' with Gradle 2.14.1
 *
 * @author skobr, @date 10/29/17 7:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
